let student1 = new Student("Tony", "male", 37);
student1.addMark(1, "algebra");
student1.addMark(5, "algebra");
student1.addMark(4, "bio");
student1.addMark(3, "bio");
student1.addMark(0, "bio");
student1.addMark(5, "geo");
student1.getAverageBySubject("bio");
student1.getAverageBySubject("rus");
console.log(student1); 
student1.exclude("Исключен за попытку подделать оценки");
console.log(student1); 